### ISSUE TITLE
Windows support ?

### ISSUE THREAD

**Issue by dmerejkowsky** [dschep/install-poetry-action#6]
There's a check of this action on Windows, but it fails here:

```
##[error]There was an error when attempting to execute the process 'poetry'. This may indicate the process failed to start. Error: spawn poetry ENOENT
```

Not sure where the issue is, but if this action does not work on Windows, I guess it deserves a mention in the doc

**Comment by dschep** [comment]
Yeah, not sure why it stopped working. I don't think I made a change that caused it to break. Alas... updating the readme will more likely be to reflect I don't maintain this any more :/

**Comment by dmerejkowsky** [comment]
On the other hand, this works on the three operating systems (assuming `pytest` is a dev dep):

```yaml
    - name: Install and configure poetry
      run: |
        python -m pip install poetry
        python -m poetry config virtualenvs.create false

    - name: Prepare project for development
      run: python -m poetry install

    - name: Run tests
      run: |
        python -m pytest 
```

See full example here: https://github.com/dmerejkowsky/python-cli-ui/blob/master/.github/workflows/tests.yml

So there :)
